services:
  - type: web
    name: taaa-semantic-extractor
    env: python
    plan: free
    buildCommand: pip install -r app/requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
