services:
  - type: web
    name: taaa-semantic-analyzer
    env: python
    buildCommand: |
      apt-get update && apt-get install -y fonts-noto-cjk
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: cd app && uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000
    staticPublishPath: app/static
